---
kube-bench:
  cronjob:
    schedule: "0 0 * * *"
    command: ["kube-bench", "run", "--targets", "master,node,etcd,controlplane,policies", "--benchmark", "cis-1.10"]

  image:
    repository: aquasec/kube-bench
    tag: v0.8.0
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
  # runAsUser: 1000

  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 50Mi
  nodeSelector: {}
  tolerations:
  - operator: "Exists"
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
  concurrencyPolicy: Forbid
  volumes:
    - name: var-lib-cni
      hostPath:
        path: "/var/lib/cni"
    - name: var-lib-etcd
      hostPath:
        path: "/var/lib/etcddisk/etcd"
    - name: var-lib-kubelet
      hostPath:
        path: "/var/lib/kubelet"
    - name: var-lib-kube-scheduler
      hostPath:
        path: "/var/lib/kube-scheduler"
    - name: var-lib-kube-controller-manager
      hostPath:
        path: "/var/lib/kube-controller-manager"
    - name: etc-systemd
      hostPath:
        path: "/etc/systemd"
    - name: lib-systemd
      hostPath:
        path: "/lib/systemd"
    - name: srv-kubernetes
      hostPath:
        path: "/srv/kubernetes"
    - name: etc-kubernetes
      hostPath:
        path: "/etc/kubernetes"
    - name: usr-bin
      hostPath:
        path: "/usr/bin"
    - name: etc-cni-netd
      hostPath:
        path: "/etc/cni/net.d/"
    - name: opt-cni-bin
      hostPath:
        path: "/opt/cni/bin/"
    - name: etc-passwd
      hostPath:
        path: "/etc/passwd"
    - name: etc-group
      hostPath:
        path: "/etc/group"
  volumeMounts:
    - name: var-lib-cni
      mountPath: /var/lib/cni
      readOnly: true
    - name: var-lib-etcd
      mountPath: /var/lib/etcddisk/etcd
      readOnly: true
    - name: var-lib-kubelet
      mountPath: /var/lib/kubelet
      readOnly: true
    - name: var-lib-kube-scheduler
      mountPath: /var/lib/kube-scheduler
      readOnly: true
    - name: var-lib-kube-controller-manager
      mountPath: /var/lib/kube-controller-manager
      readOnly: true
    - name: etc-systemd
      mountPath: /etc/systemd
      readOnly: true
    - name: lib-systemd
      mountPath: /lib/systemd/
      readOnly: true
    - name: srv-kubernetes
      mountPath: /srv/kubernetes/
      readOnly: true
    - name: etc-kubernetes
      mountPath: /etc/kubernetes
      readOnly: true
    - name: usr-bin
      mountPath: /usr/local/mount-from-host/bin
      readOnly: true
    - name: etc-cni-netd
      mountPath: /etc/cni/net.d/
      readOnly: true
    - name: opt-cni-bin
      mountPath: /opt/cni/bin/
      readOnly: true
    - name: etc-passwd
      mountPath: /etc/passwd
      readOnly: true
    - name: etc-group
      mountPath: /etc/group
      readOnly: true