apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: azure-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${emailAddress}
    privateKeySecretRef:                                                                   
      name: letsencrypt-cluster-issuer-key
    solvers:
    - dns01:
        azureDNS:
          clientID: ${servicePrincipalClientId}
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: ${subscriptionId}
          tenantID: ${tenantId}
          resourceGroupName: mgmt-cluster
          hostedZoneName: lndbrg.tech
          environment: AzurePublicCloud