apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: git-repository
  namespace: argocd
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      eitsCluster: enabled
  resources:
    - name: git-repository
      kind: Secret