apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: azure-sp-credentials
  namespace: capi-ha
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      clusterName: capi-ha
  resources:
    - name: azure-sp-credentials
      kind: Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-sp-credentials
  namespace: capi-ha
type: addons.cluster.x-k8s.io/resource-set
stringData:
  eso.yaml: |-
    apiVersion: v1
    data:
      ClientID: ${servicePrincipalClientId}
      ClientSecret: ${servicePrincipalClientSecret}
    kind: Secret
    metadata:
      name: azure-sp-secret
      namespace: external-secrets
