apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: azure-sp-secret
  namespace: external-dns
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      clusterName: capi-ha
  resources:
    - name: azure-sp-secret
      kind: Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-sp-secret
  namespace: capi-ha
type: addons.cluster.x-k8s.io/resource-set
stringData:
  externaldns.yaml: |-
    apiVersion: v1
    data:
      azure.json: ${azureJson}
    kind: Secret
    metadata:
      name: azure-sp-secret
      namespace: external-dns
