apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: azure-sp-secret
  namespace: external-dns
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      clusterName: capi-ha
  resources:
    - name: azure-sp-secret
      kind: Secret