apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: "${tenantId}"
      vaultUrl: "${vaultUrl}"
      authSecretRef:
        clientId:
          name: azure-sp-secret
          key: ClientID
        clientSecret:
          name: azure-sp-secret
          key: ClientSecret