apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cloud-provider-azure-chart
  namespace: capi-ha
spec:
  clusterSelector:
    matchLabels:
      eitsCluster: enabled
  repoURL: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo
  chartName: cloud-provider-azure
  version: 1.32.4
  releaseName: cloud-provider-azure-oot
  valuesTemplate: |
    infra:
      clusterName: capi-ha
    cloudControllerManager:
      clusterCIDR: 192.168.0.0/16
      logVerbosity: 4