apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: haproxy
  namespace: capi-ha
spec:
  clusterSelector:
    matchLabels:
      eitsCluster: enabled
  repoURL: https://haproxytech.github.io/helm-charts
  chartName: kubernetes-ingress
  version: 1.24.0
  releaseName: haproxy-kubernetes-ingress
  namespace: haproxy-controller
  valuesTemplate: |
    controller:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - capi-ha-ingress000000
                - capi-ha-ingress000001
      tolerations:
      - key: "ingress"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 80m
          memory: 80Mi