# /etc/kubernetes/auth-config.yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
anonymous:
  #  - --anonymous-auth=false # disable globally
  #  - --authentication-config=/etc/kubernetes/auth-config.yaml 
  # Enable anonymous access ONLY for the paths listed below
  enabled: true
  conditions:
  - path: /metrics
  - path: /readyz
  - path: /ready
  - path: /healthz
  - path: /health
  - path: /healthy
  - path: /liveness
  - path: /
  - path: /readiness
  - path: /livez
  - path: /healthz?full=true