# head -c 32 /dev/urandom | base64
# This creates a random 32-byte key for 'secretbox' encryption
---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: '[REDACTED]'
      - identity: {} #fallback