kubernetes-ingress:
  controller:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
              - capi-ha-ingress000000
              - capi-ha-ingress000001
    tolerations:
    - key: "ingress"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 80m
        memory: 80Mi