apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: workload/apps/monitoring/kube-prometheus-stack
    repoURL: https://github.com/mlndbr6/e-its-kubernetes
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    # - Replace=true # Required for initial installation to get around 'kubectl apply' exceeding size limits.