apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restarter
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: restarter
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
      ignoreMissingValueFiles: true
    path: workload/apps/restarter
    repoURL: https://github.com/mlndbr6/e-its-kubernetes
    targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio.io/dataplane-mode: ambient
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true