apiVersion: v2
name: loki
description: A chart to deploy Grafana Loki for central logging solution
type: application
version: 6.29.0
appVersion: 6.29.0

dependencies:
- name: loki
  version: 6.29.0
  repository: https://grafana.github.io/helm-charts